import { MigrationInterface, QueryRunner } from "typeorm";

export class IndicesAbogado1769313940453 implements MigrationInterface {
    name = 'IndicesAbogado1769313940453'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`files\` DROP FOREIGN KEY \`FK_3847bce5b766d69c2d0e320b1ef\``);
        await queryRunner.query(`ALTER TABLE \`files\` DROP FOREIGN KEY \`FK_45969913e1276f23c44c04ab30b\``);
        await queryRunner.query(`ALTER TABLE \`files\` DROP FOREIGN KEY \`FK_6ea47570ecb59c0fd0ce6b784be\``);
        await queryRunner.query(`ALTER TABLE \`files\` DROP FOREIGN KEY \`FK_889080ced09b49ebb4c8fb005db\``);
        await queryRunner.query(`ALTER TABLE \`pagos\` DROP FOREIGN KEY \`FK_3fa5cbaf018b1004741ff1afca5\``);
        await queryRunner.query(`ALTER TABLE \`pagos\` DROP FOREIGN KEY \`FK_ed9e32bfd96f130ffa862adbcc9\``);
        await queryRunner.query(`ALTER TABLE \`pagos\` DROP FOREIGN KEY \`FK_ef854a8e14a8828e5586afbe215\``);
        await queryRunner.query(`ALTER TABLE \`progresos_trabajo\` DROP FOREIGN KEY \`FK_577742b42abc00bcdb8f9b039b8\``);
        await queryRunner.query(`ALTER TABLE \`pagos_abogado\` DROP FOREIGN KEY \`FK_100ca65fd5f8c99c052aa746156\``);
        await queryRunner.query(`ALTER TABLE \`pagos_abogado\` DROP FOREIGN KEY \`FK_2779f73fd4282ba52c7b58958ab\``);
        await queryRunner.query(`ALTER TABLE \`trabajos\` DROP FOREIGN KEY \`FK_14b883832a7729bda1586e6af23\``);
        await queryRunner.query(`ALTER TABLE \`trabajos\` DROP FOREIGN KEY \`FK_31161729ac9b11c19eb0117f81a\``);
        await queryRunner.query(`ALTER TABLE \`trabajos\` DROP FOREIGN KEY \`FK_8099fd79318587093f6bf4b83bf\``);
        await queryRunner.query(`ALTER TABLE \`preguntas_oferta\` DROP FOREIGN KEY \`FK_d514c3c7a019638115c025fb5db\``);
        await queryRunner.query(`ALTER TABLE \`respuestas_oferta\` DROP FOREIGN KEY \`FK_ba7f1f593bbea35a0cb857a4f14\``);
        await queryRunner.query(`ALTER TABLE \`respuestas_oferta\` DROP FOREIGN KEY \`FK_f3e8713cb58b6c866b56ce9d3b8\``);
        await queryRunner.query(`ALTER TABLE \`aplicaciones\` DROP FOREIGN KEY \`FK_c10d043d672443bb0f4a5106b25\``);
        await queryRunner.query(`ALTER TABLE \`aplicaciones\` DROP FOREIGN KEY \`FK_dc60683a7b4e357d4d5bffa1698\``);
        await queryRunner.query(`ALTER TABLE \`servicios_abogado\` DROP FOREIGN KEY \`FK_130434f31f7fd13567b51b51c7e\``);
        await queryRunner.query(`ALTER TABLE \`servicios_abogado\` DROP FOREIGN KEY \`FK_e874304bdce46393e0a14bd7b52\``);
        await queryRunner.query(`ALTER TABLE \`servicios_oferta\` DROP FOREIGN KEY \`FK_5d4bebcd4ecc658ee52ef175b4d\``);
        await queryRunner.query(`ALTER TABLE \`servicios_oferta\` DROP FOREIGN KEY \`FK_73a4ab4c25d2f51c834b2ec6b5f\``);
        await queryRunner.query(`ALTER TABLE \`industrias_abogado\` DROP FOREIGN KEY \`FK_879d25a9cd6e5585fe4b586b684\``);
        await queryRunner.query(`ALTER TABLE \`industrias_abogado\` DROP FOREIGN KEY \`FK_ca773a8572eca954c744df62065\``);
        await queryRunner.query(`ALTER TABLE \`industrias_oferta\` DROP FOREIGN KEY \`FK_37d0b01ae96c4012c22ec03478d\``);
        await queryRunner.query(`ALTER TABLE \`industrias_oferta\` DROP FOREIGN KEY \`FK_92a2e52e5974eb44e81d95c7873\``);
        await queryRunner.query(`ALTER TABLE \`especialidades_abogado\` DROP FOREIGN KEY \`FK_9f3e8c9ae442054de33f1dfe915\``);
        await queryRunner.query(`ALTER TABLE \`especialidades_abogado\` DROP FOREIGN KEY \`FK_a17f29b9fcd3a66691c973b1d65\``);
        await queryRunner.query(`ALTER TABLE \`especialidades_oferta\` DROP FOREIGN KEY \`FK_13defeddcd8b6e6c6c32be6e68a\``);
        await queryRunner.query(`ALTER TABLE \`especialidades_oferta\` DROP FOREIGN KEY \`FK_5415a3af5f5df95ea327ce10636\``);
        await queryRunner.query(`ALTER TABLE \`invitaciones\` DROP FOREIGN KEY \`FK_6a3e65a910f213c66b40e66b413\``);
        await queryRunner.query(`ALTER TABLE \`invitaciones\` DROP FOREIGN KEY \`FK_7a06641e7ce67e750ac3634a321\``);
        await queryRunner.query(`ALTER TABLE \`ofertas\` DROP FOREIGN KEY \`FK_bd29657fa3c0e45193334e16989\``);
        await queryRunner.query(`ALTER TABLE \`usuarios\` DROP FOREIGN KEY \`FK_3d24dbe988e1186ec0bc6f4d165\``);
        await queryRunner.query(`ALTER TABLE \`usuarios\` DROP FOREIGN KEY \`FK_5f4dc9b4cf1f7993658c5c22927\``);
        await queryRunner.query(`ALTER TABLE \`habilidades_blandas\` DROP FOREIGN KEY \`FK_f6847ca550afe2c575adf0cc813\``);
        await queryRunner.query(`ALTER TABLE \`habilidades_duras\` DROP FOREIGN KEY \`FK_fd2feb177ffd5609bf1030cc457\``);
        await queryRunner.query(`ALTER TABLE \`experiencias\` DROP FOREIGN KEY \`FK_36c4a935245dc22dceb21568586\``);
        await queryRunner.query(`ALTER TABLE \`educaciones\` DROP FOREIGN KEY \`FK_aa99d5b415317d1ae3fb4d844f5\``);
        await queryRunner.query(`ALTER TABLE \`libro_reclamaciones\` CHANGE \`doomicilio\` \`domicilio\` varchar(255) COLLATE "utf8mb4_0900_ai_ci" NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`files\` CHANGE \`deleted_at\` \`deleted_at\` timestamp(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`files\` CHANGE \`dni\` \`dni\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`files\` CHANGE \`correo\` \`correo\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`files\` CHANGE \`id_front\` \`id_front\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`files\` CHANGE \`abogado_id\` \`abogado_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`files\` CHANGE \`oferta_id\` \`oferta_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`files\` CHANGE \`aplicacion_id\` \`aplicacion_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`files\` CHANGE \`trabajo_id\` \`trabajo_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`pagos\` CHANGE \`deleted_at\` \`deleted_at\` timestamp(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`pagos\` CHANGE \`monto_abogado\` \`monto_abogado\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`pagos\` CHANGE \`direccion_factura\` \`direccion_factura\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`pagos\` CHANGE \`nombre_factura\` \`nombre_factura\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`pagos\` CHANGE \`ruc\` \`ruc\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`pagos\` CHANGE \`trabajo_id\` \`trabajo_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`pagos\` CHANGE \`cliente_id\` \`cliente_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`pagos\` CHANGE \`abogado_id\` \`abogado_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`progresos_trabajo\` CHANGE \`deleted_at\` \`deleted_at\` timestamp(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`progresos_trabajo\` CHANGE \`descripcion\` \`descripcion\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`progresos_trabajo\` CHANGE \`progreso\` \`progreso\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`progresos_trabajo\` CHANGE \`documento\` \`documento\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`progresos_trabajo\` CHANGE \`estado\` \`estado\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`progresos_trabajo\` CHANGE \`trabajo_id\` \`trabajo_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`pagos_abogado\` CHANGE \`deleted_at\` \`deleted_at\` timestamp(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`pagos_abogado\` CHANGE \`tipo_pago\` \`tipo_pago\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`pagos_abogado\` CHANGE \`trabajo_id\` \`trabajo_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`pagos_abogado\` CHANGE \`abogado_id\` \`abogado_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`trabajos\` CHANGE \`deleted_at\` \`deleted_at\` timestamp(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`trabajos\` CHANGE \`estado\` \`estado\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`trabajos\` CHANGE \`fecha_fin\` \`fecha_fin\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`trabajos\` CHANGE \`progreso\` \`progreso\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`trabajos\` CHANGE \`cliente_id\` \`cliente_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`trabajos\` CHANGE \`abogado_id\` \`abogado_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`trabajos\` CHANGE \`aplicacion_id\` \`aplicacion_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`preguntas_oferta\` CHANGE \`deleted_at\` \`deleted_at\` timestamp(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`preguntas_oferta\` CHANGE \`respuesta\` \`respuesta\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`preguntas_oferta\` CHANGE \`oferta_id\` \`oferta_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`respuestas_oferta\` CHANGE \`deleted_at\` \`deleted_at\` timestamp(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`respuestas_oferta\` CHANGE \`respuesta\` \`respuesta\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`respuestas_oferta\` CHANGE \`pregunta_id\` \`pregunta_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`respuestas_oferta\` CHANGE \`aplicacion_id\` \`aplicacion_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`aplicaciones\` CHANGE \`deleted_at\` \`deleted_at\` timestamp(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`aplicaciones\` DROP COLUMN \`fecha_aplicacion\``);
        await queryRunner.query(`ALTER TABLE \`aplicaciones\` ADD \`fecha_aplicacion\` date NULL`);
        await queryRunner.query(`ALTER TABLE \`aplicaciones\` CHANGE \`numero_cuenta\` \`numero_cuenta\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`aplicaciones\` CHANGE \`numero_cuenta_cci\` \`numero_cuenta_cci\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`aplicaciones\` CHANGE \`selected_banco\` \`selected_banco\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`aplicaciones\` CHANGE \`estado\` \`estado\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`aplicaciones\` CHANGE \`salario_esperado\` \`salario_esperado\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`aplicaciones\` CHANGE \`comision\` \`comision\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`aplicaciones\` CHANGE \`impuesto\` \`impuesto\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`aplicaciones\` CHANGE \`salario_real\` \`salario_real\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`aplicaciones\` CHANGE \`oferta_id\` \`oferta_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`aplicaciones\` CHANGE \`abogado_id\` \`abogado_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`servicios_abogado\` CHANGE \`abogado_id\` \`abogado_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`servicios_abogado\` CHANGE \`servicio_id\` \`servicio_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`servicios\` CHANGE \`deleted_at\` \`deleted_at\` timestamp(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`servicios_oferta\` CHANGE \`oferta_id\` \`oferta_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`servicios_oferta\` CHANGE \`servicio_id\` \`servicio_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`industrias_abogado\` CHANGE \`abogado_id\` \`abogado_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`industrias_abogado\` CHANGE \`industria_id\` \`industria_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`industrias\` CHANGE \`deleted_at\` \`deleted_at\` timestamp(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`industrias_oferta\` CHANGE \`oferta_id\` \`oferta_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`industrias_oferta\` CHANGE \`industria_id\` \`industria_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`especialidades_abogado\` CHANGE \`abogado_id\` \`abogado_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`especialidades_abogado\` CHANGE \`especialidad_id\` \`especialidad_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`especialidades\` CHANGE \`deleted_at\` \`deleted_at\` timestamp(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`especialidades_oferta\` CHANGE \`oferta_id\` \`oferta_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`especialidades_oferta\` CHANGE \`especialidad_id\` \`especialidad_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`invitaciones\` CHANGE \`deleted_at\` \`deleted_at\` timestamp(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`invitaciones\` CHANGE \`mensaje\` \`mensaje\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`invitaciones\` CHANGE \`estado\` \`estado\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`invitaciones\` DROP COLUMN \`fecha_invitacion\``);
        await queryRunner.query(`ALTER TABLE \`invitaciones\` ADD \`fecha_invitacion\` date NULL`);
        await queryRunner.query(`ALTER TABLE \`invitaciones\` DROP COLUMN \`fecha_respuesta\``);
        await queryRunner.query(`ALTER TABLE \`invitaciones\` ADD \`fecha_respuesta\` date NULL`);
        await queryRunner.query(`ALTER TABLE \`invitaciones\` CHANGE \`oferta_id\` \`oferta_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`invitaciones\` CHANGE \`abogado_id\` \`abogado_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`ofertas\` CHANGE \`deleted_at\` \`deleted_at\` timestamp(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`ofertas\` CHANGE \`uso\` \`uso\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`ofertas\` CHANGE \`titulo\` \`titulo\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`ofertas\` CHANGE \`documento_url\` \`documento_url\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`ofertas\` CHANGE \`duracion\` \`duracion\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`ofertas\` CHANGE \`experiencia_abogado\` \`experiencia_abogado\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`ofertas\` CHANGE \`salario_minimo\` \`salario_minimo\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`ofertas\` CHANGE \`salario_maximo\` \`salario_maximo\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`ofertas\` CHANGE \`estado\` \`estado\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`ofertas\` CHANGE \`fecha_expiracion\` \`fecha_expiracion\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`ofertas\` CHANGE \`cliente_id\` \`cliente_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`clientes\` CHANGE \`deleted_at\` \`deleted_at\` timestamp(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`clientes\` CHANGE \`razon_social\` \`razon_social\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`usuarios\` CHANGE \`deleted_at\` \`deleted_at\` timestamp(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`usuarios\` CHANGE \`direccion\` \`direccion\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`usuarios\` CHANGE \`activation_code\` \`activation_code\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`usuarios\` CHANGE \`activation_code_expires\` \`activation_code_expires\` timestamp NULL`);
        await queryRunner.query(`ALTER TABLE \`usuarios\` CHANGE \`abogado_id\` \`abogado_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`usuarios\` CHANGE \`cliente_id\` \`cliente_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`habilidades_blandas\` CHANGE \`deleted_at\` \`deleted_at\` timestamp(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`habilidades_blandas\` CHANGE \`abogado_id\` \`abogado_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`habilidades_duras\` CHANGE \`deleted_at\` \`deleted_at\` timestamp(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`habilidades_duras\` CHANGE \`abogado_id\` \`abogado_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`experiencias\` CHANGE \`deleted_at\` \`deleted_at\` timestamp(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`experiencias\` DROP COLUMN \`fecha_fin\``);
        await queryRunner.query(`ALTER TABLE \`experiencias\` ADD \`fecha_fin\` date NULL`);
        await queryRunner.query(`ALTER TABLE \`experiencias\` DROP COLUMN \`fecha_inicio\``);
        await queryRunner.query(`ALTER TABLE \`experiencias\` ADD \`fecha_inicio\` date NULL`);
        await queryRunner.query(`ALTER TABLE \`experiencias\` CHANGE \`abogado_id\` \`abogado_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`educaciones\` CHANGE \`deleted_at\` \`deleted_at\` timestamp(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`educaciones\` DROP COLUMN \`fecha_fin\``);
        await queryRunner.query(`ALTER TABLE \`educaciones\` ADD \`fecha_fin\` date NULL`);
        await queryRunner.query(`ALTER TABLE \`educaciones\` DROP COLUMN \`fecha_inicio\``);
        await queryRunner.query(`ALTER TABLE \`educaciones\` ADD \`fecha_inicio\` date NULL`);
        await queryRunner.query(`ALTER TABLE \`educaciones\` CHANGE \`descripcion\` \`descripcion\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`educaciones\` CHANGE \`abogado_id\` \`abogado_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`abogados\` CHANGE \`deleted_at\` \`deleted_at\` timestamp(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`abogados\` CHANGE \`cip\` \`cip\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`abogados\` CHANGE \`ruc\` \`ruc\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`abogados\` CHANGE \`colegio\` \`colegio\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`abogados\` CHANGE \`objetivo\` \`objetivo\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`perfiles\` CHANGE \`deleted_at\` \`deleted_at\` timestamp(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`libro_reclamaciones\` CHANGE \`deleted_at\` \`deleted_at\` timestamp(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`libro_reclamaciones\` DROP COLUMN \`domicilio\``);
        await queryRunner.query(`ALTER TABLE \`libro_reclamaciones\` ADD \`domicilio\` varchar(255) NOT NULL`);
        await queryRunner.query(`CREATE INDEX \`idx_files_abogado\` ON \`files\` (\`abogado_id\`)`);
        await queryRunner.query(`CREATE INDEX \`idx_pagos_abogado\` ON \`pagos\` (\`abogado_id\`)`);
        await queryRunner.query(`CREATE INDEX \`idx_trabajos_abogado\` ON \`trabajos\` (\`abogado_id\`)`);
        await queryRunner.query(`CREATE INDEX \`idx_aplicaciones_abogado\` ON \`aplicaciones\` (\`abogado_id\`)`);
        await queryRunner.query(`CREATE INDEX \`idx_servicios_abogado\` ON \`servicios_abogado\` (\`abogado_id\`)`);
        await queryRunner.query(`CREATE INDEX \`idx_industrias_abogado\` ON \`industrias_abogado\` (\`abogado_id\`)`);
        await queryRunner.query(`CREATE INDEX \`idx_especialidades_abogado\` ON \`especialidades_abogado\` (\`abogado_id\`)`);
        await queryRunner.query(`CREATE INDEX \`idx_invitaciones_abogado\` ON \`invitaciones\` (\`abogado_id\`)`);
        await queryRunner.query(`CREATE INDEX \`idx_usuario_abogado\` ON \`usuarios\` (\`abogado_id\`)`);
        await queryRunner.query(`CREATE INDEX \`idx_habilidades_blanda_abogado\` ON \`habilidades_blandas\` (\`abogado_id\`)`);
        await queryRunner.query(`CREATE INDEX \`idx_habilidades_dura_abogado\` ON \`habilidades_duras\` (\`abogado_id\`)`);
        await queryRunner.query(`CREATE INDEX \`idx_experiencias_abogado\` ON \`experiencias\` (\`abogado_id\`)`);
        await queryRunner.query(`CREATE INDEX \`idx_educaciones_abogado\` ON \`educaciones\` (\`abogado_id\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_516ba850f99d4b6db4d54f66a8\` ON \`abogados\` (\`validado_admin\`, \`created_at\`)`);
        await queryRunner.query(`ALTER TABLE \`files\` ADD CONSTRAINT \`FK_889080ced09b49ebb4c8fb005db\` FOREIGN KEY (\`abogado_id\`) REFERENCES \`abogados\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`files\` ADD CONSTRAINT \`FK_3847bce5b766d69c2d0e320b1ef\` FOREIGN KEY (\`oferta_id\`) REFERENCES \`ofertas\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`files\` ADD CONSTRAINT \`FK_6ea47570ecb59c0fd0ce6b784be\` FOREIGN KEY (\`aplicacion_id\`) REFERENCES \`aplicaciones\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`files\` ADD CONSTRAINT \`FK_45969913e1276f23c44c04ab30b\` FOREIGN KEY (\`trabajo_id\`) REFERENCES \`trabajos\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`pagos\` ADD CONSTRAINT \`FK_ed9e32bfd96f130ffa862adbcc9\` FOREIGN KEY (\`trabajo_id\`) REFERENCES \`trabajos\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`pagos\` ADD CONSTRAINT \`FK_3fa5cbaf018b1004741ff1afca5\` FOREIGN KEY (\`cliente_id\`) REFERENCES \`clientes\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`pagos\` ADD CONSTRAINT \`FK_ef854a8e14a8828e5586afbe215\` FOREIGN KEY (\`abogado_id\`) REFERENCES \`abogados\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`progresos_trabajo\` ADD CONSTRAINT \`FK_577742b42abc00bcdb8f9b039b8\` FOREIGN KEY (\`trabajo_id\`) REFERENCES \`trabajos\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`pagos_abogado\` ADD CONSTRAINT \`FK_2779f73fd4282ba52c7b58958ab\` FOREIGN KEY (\`trabajo_id\`) REFERENCES \`trabajos\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`pagos_abogado\` ADD CONSTRAINT \`FK_100ca65fd5f8c99c052aa746156\` FOREIGN KEY (\`abogado_id\`) REFERENCES \`abogados\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`trabajos\` ADD CONSTRAINT \`FK_14b883832a7729bda1586e6af23\` FOREIGN KEY (\`cliente_id\`) REFERENCES \`clientes\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`trabajos\` ADD CONSTRAINT \`FK_8099fd79318587093f6bf4b83bf\` FOREIGN KEY (\`abogado_id\`) REFERENCES \`abogados\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`trabajos\` ADD CONSTRAINT \`FK_31161729ac9b11c19eb0117f81a\` FOREIGN KEY (\`aplicacion_id\`) REFERENCES \`aplicaciones\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`preguntas_oferta\` ADD CONSTRAINT \`FK_d514c3c7a019638115c025fb5db\` FOREIGN KEY (\`oferta_id\`) REFERENCES \`ofertas\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`respuestas_oferta\` ADD CONSTRAINT \`FK_ba7f1f593bbea35a0cb857a4f14\` FOREIGN KEY (\`pregunta_id\`) REFERENCES \`preguntas_oferta\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`respuestas_oferta\` ADD CONSTRAINT \`FK_f3e8713cb58b6c866b56ce9d3b8\` FOREIGN KEY (\`aplicacion_id\`) REFERENCES \`aplicaciones\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`aplicaciones\` ADD CONSTRAINT \`FK_c10d043d672443bb0f4a5106b25\` FOREIGN KEY (\`oferta_id\`) REFERENCES \`ofertas\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`aplicaciones\` ADD CONSTRAINT \`FK_dc60683a7b4e357d4d5bffa1698\` FOREIGN KEY (\`abogado_id\`) REFERENCES \`abogados\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`servicios_abogado\` ADD CONSTRAINT \`FK_e874304bdce46393e0a14bd7b52\` FOREIGN KEY (\`abogado_id\`) REFERENCES \`abogados\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`servicios_abogado\` ADD CONSTRAINT \`FK_130434f31f7fd13567b51b51c7e\` FOREIGN KEY (\`servicio_id\`) REFERENCES \`servicios\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`servicios_oferta\` ADD CONSTRAINT \`FK_5d4bebcd4ecc658ee52ef175b4d\` FOREIGN KEY (\`oferta_id\`) REFERENCES \`ofertas\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`servicios_oferta\` ADD CONSTRAINT \`FK_73a4ab4c25d2f51c834b2ec6b5f\` FOREIGN KEY (\`servicio_id\`) REFERENCES \`servicios\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`industrias_abogado\` ADD CONSTRAINT \`FK_879d25a9cd6e5585fe4b586b684\` FOREIGN KEY (\`abogado_id\`) REFERENCES \`abogados\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`industrias_abogado\` ADD CONSTRAINT \`FK_ca773a8572eca954c744df62065\` FOREIGN KEY (\`industria_id\`) REFERENCES \`industrias\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`industrias_oferta\` ADD CONSTRAINT \`FK_37d0b01ae96c4012c22ec03478d\` FOREIGN KEY (\`oferta_id\`) REFERENCES \`ofertas\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`industrias_oferta\` ADD CONSTRAINT \`FK_92a2e52e5974eb44e81d95c7873\` FOREIGN KEY (\`industria_id\`) REFERENCES \`industrias\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`especialidades_abogado\` ADD CONSTRAINT \`FK_a17f29b9fcd3a66691c973b1d65\` FOREIGN KEY (\`abogado_id\`) REFERENCES \`abogados\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`especialidades_abogado\` ADD CONSTRAINT \`FK_9f3e8c9ae442054de33f1dfe915\` FOREIGN KEY (\`especialidad_id\`) REFERENCES \`especialidades\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`especialidades_oferta\` ADD CONSTRAINT \`FK_5415a3af5f5df95ea327ce10636\` FOREIGN KEY (\`oferta_id\`) REFERENCES \`ofertas\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`especialidades_oferta\` ADD CONSTRAINT \`FK_13defeddcd8b6e6c6c32be6e68a\` FOREIGN KEY (\`especialidad_id\`) REFERENCES \`especialidades\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`invitaciones\` ADD CONSTRAINT \`FK_7a06641e7ce67e750ac3634a321\` FOREIGN KEY (\`oferta_id\`) REFERENCES \`ofertas\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`invitaciones\` ADD CONSTRAINT \`FK_6a3e65a910f213c66b40e66b413\` FOREIGN KEY (\`abogado_id\`) REFERENCES \`abogados\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`ofertas\` ADD CONSTRAINT \`FK_bd29657fa3c0e45193334e16989\` FOREIGN KEY (\`cliente_id\`) REFERENCES \`clientes\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`usuarios\` ADD CONSTRAINT \`FK_3d24dbe988e1186ec0bc6f4d165\` FOREIGN KEY (\`abogado_id\`) REFERENCES \`abogados\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`usuarios\` ADD CONSTRAINT \`FK_5f4dc9b4cf1f7993658c5c22927\` FOREIGN KEY (\`cliente_id\`) REFERENCES \`clientes\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`habilidades_blandas\` ADD CONSTRAINT \`FK_f6847ca550afe2c575adf0cc813\` FOREIGN KEY (\`abogado_id\`) REFERENCES \`abogados\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`habilidades_duras\` ADD CONSTRAINT \`FK_fd2feb177ffd5609bf1030cc457\` FOREIGN KEY (\`abogado_id\`) REFERENCES \`abogados\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`experiencias\` ADD CONSTRAINT \`FK_36c4a935245dc22dceb21568586\` FOREIGN KEY (\`abogado_id\`) REFERENCES \`abogados\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`educaciones\` ADD CONSTRAINT \`FK_aa99d5b415317d1ae3fb4d844f5\` FOREIGN KEY (\`abogado_id\`) REFERENCES \`abogados\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`educaciones\` DROP FOREIGN KEY \`FK_aa99d5b415317d1ae3fb4d844f5\``);
        await queryRunner.query(`ALTER TABLE \`experiencias\` DROP FOREIGN KEY \`FK_36c4a935245dc22dceb21568586\``);
        await queryRunner.query(`ALTER TABLE \`habilidades_duras\` DROP FOREIGN KEY \`FK_fd2feb177ffd5609bf1030cc457\``);
        await queryRunner.query(`ALTER TABLE \`habilidades_blandas\` DROP FOREIGN KEY \`FK_f6847ca550afe2c575adf0cc813\``);
        await queryRunner.query(`ALTER TABLE \`usuarios\` DROP FOREIGN KEY \`FK_5f4dc9b4cf1f7993658c5c22927\``);
        await queryRunner.query(`ALTER TABLE \`usuarios\` DROP FOREIGN KEY \`FK_3d24dbe988e1186ec0bc6f4d165\``);
        await queryRunner.query(`ALTER TABLE \`ofertas\` DROP FOREIGN KEY \`FK_bd29657fa3c0e45193334e16989\``);
        await queryRunner.query(`ALTER TABLE \`invitaciones\` DROP FOREIGN KEY \`FK_6a3e65a910f213c66b40e66b413\``);
        await queryRunner.query(`ALTER TABLE \`invitaciones\` DROP FOREIGN KEY \`FK_7a06641e7ce67e750ac3634a321\``);
        await queryRunner.query(`ALTER TABLE \`especialidades_oferta\` DROP FOREIGN KEY \`FK_13defeddcd8b6e6c6c32be6e68a\``);
        await queryRunner.query(`ALTER TABLE \`especialidades_oferta\` DROP FOREIGN KEY \`FK_5415a3af5f5df95ea327ce10636\``);
        await queryRunner.query(`ALTER TABLE \`especialidades_abogado\` DROP FOREIGN KEY \`FK_9f3e8c9ae442054de33f1dfe915\``);
        await queryRunner.query(`ALTER TABLE \`especialidades_abogado\` DROP FOREIGN KEY \`FK_a17f29b9fcd3a66691c973b1d65\``);
        await queryRunner.query(`ALTER TABLE \`industrias_oferta\` DROP FOREIGN KEY \`FK_92a2e52e5974eb44e81d95c7873\``);
        await queryRunner.query(`ALTER TABLE \`industrias_oferta\` DROP FOREIGN KEY \`FK_37d0b01ae96c4012c22ec03478d\``);
        await queryRunner.query(`ALTER TABLE \`industrias_abogado\` DROP FOREIGN KEY \`FK_ca773a8572eca954c744df62065\``);
        await queryRunner.query(`ALTER TABLE \`industrias_abogado\` DROP FOREIGN KEY \`FK_879d25a9cd6e5585fe4b586b684\``);
        await queryRunner.query(`ALTER TABLE \`servicios_oferta\` DROP FOREIGN KEY \`FK_73a4ab4c25d2f51c834b2ec6b5f\``);
        await queryRunner.query(`ALTER TABLE \`servicios_oferta\` DROP FOREIGN KEY \`FK_5d4bebcd4ecc658ee52ef175b4d\``);
        await queryRunner.query(`ALTER TABLE \`servicios_abogado\` DROP FOREIGN KEY \`FK_130434f31f7fd13567b51b51c7e\``);
        await queryRunner.query(`ALTER TABLE \`servicios_abogado\` DROP FOREIGN KEY \`FK_e874304bdce46393e0a14bd7b52\``);
        await queryRunner.query(`ALTER TABLE \`aplicaciones\` DROP FOREIGN KEY \`FK_dc60683a7b4e357d4d5bffa1698\``);
        await queryRunner.query(`ALTER TABLE \`aplicaciones\` DROP FOREIGN KEY \`FK_c10d043d672443bb0f4a5106b25\``);
        await queryRunner.query(`ALTER TABLE \`respuestas_oferta\` DROP FOREIGN KEY \`FK_f3e8713cb58b6c866b56ce9d3b8\``);
        await queryRunner.query(`ALTER TABLE \`respuestas_oferta\` DROP FOREIGN KEY \`FK_ba7f1f593bbea35a0cb857a4f14\``);
        await queryRunner.query(`ALTER TABLE \`preguntas_oferta\` DROP FOREIGN KEY \`FK_d514c3c7a019638115c025fb5db\``);
        await queryRunner.query(`ALTER TABLE \`trabajos\` DROP FOREIGN KEY \`FK_31161729ac9b11c19eb0117f81a\``);
        await queryRunner.query(`ALTER TABLE \`trabajos\` DROP FOREIGN KEY \`FK_8099fd79318587093f6bf4b83bf\``);
        await queryRunner.query(`ALTER TABLE \`trabajos\` DROP FOREIGN KEY \`FK_14b883832a7729bda1586e6af23\``);
        await queryRunner.query(`ALTER TABLE \`pagos_abogado\` DROP FOREIGN KEY \`FK_100ca65fd5f8c99c052aa746156\``);
        await queryRunner.query(`ALTER TABLE \`pagos_abogado\` DROP FOREIGN KEY \`FK_2779f73fd4282ba52c7b58958ab\``);
        await queryRunner.query(`ALTER TABLE \`progresos_trabajo\` DROP FOREIGN KEY \`FK_577742b42abc00bcdb8f9b039b8\``);
        await queryRunner.query(`ALTER TABLE \`pagos\` DROP FOREIGN KEY \`FK_ef854a8e14a8828e5586afbe215\``);
        await queryRunner.query(`ALTER TABLE \`pagos\` DROP FOREIGN KEY \`FK_3fa5cbaf018b1004741ff1afca5\``);
        await queryRunner.query(`ALTER TABLE \`pagos\` DROP FOREIGN KEY \`FK_ed9e32bfd96f130ffa862adbcc9\``);
        await queryRunner.query(`ALTER TABLE \`files\` DROP FOREIGN KEY \`FK_45969913e1276f23c44c04ab30b\``);
        await queryRunner.query(`ALTER TABLE \`files\` DROP FOREIGN KEY \`FK_6ea47570ecb59c0fd0ce6b784be\``);
        await queryRunner.query(`ALTER TABLE \`files\` DROP FOREIGN KEY \`FK_3847bce5b766d69c2d0e320b1ef\``);
        await queryRunner.query(`ALTER TABLE \`files\` DROP FOREIGN KEY \`FK_889080ced09b49ebb4c8fb005db\``);
        await queryRunner.query(`DROP INDEX \`IDX_516ba850f99d4b6db4d54f66a8\` ON \`abogados\``);
        await queryRunner.query(`DROP INDEX \`idx_educaciones_abogado\` ON \`educaciones\``);
        await queryRunner.query(`DROP INDEX \`idx_experiencias_abogado\` ON \`experiencias\``);
        await queryRunner.query(`DROP INDEX \`idx_habilidades_dura_abogado\` ON \`habilidades_duras\``);
        await queryRunner.query(`DROP INDEX \`idx_habilidades_blanda_abogado\` ON \`habilidades_blandas\``);
        await queryRunner.query(`DROP INDEX \`idx_usuario_abogado\` ON \`usuarios\``);
        await queryRunner.query(`DROP INDEX \`idx_invitaciones_abogado\` ON \`invitaciones\``);
        await queryRunner.query(`DROP INDEX \`idx_especialidades_abogado\` ON \`especialidades_abogado\``);
        await queryRunner.query(`DROP INDEX \`idx_industrias_abogado\` ON \`industrias_abogado\``);
        await queryRunner.query(`DROP INDEX \`idx_servicios_abogado\` ON \`servicios_abogado\``);
        await queryRunner.query(`DROP INDEX \`idx_aplicaciones_abogado\` ON \`aplicaciones\``);
        await queryRunner.query(`DROP INDEX \`idx_trabajos_abogado\` ON \`trabajos\``);
        await queryRunner.query(`DROP INDEX \`idx_pagos_abogado\` ON \`pagos\``);
        await queryRunner.query(`DROP INDEX \`idx_files_abogado\` ON \`files\``);
        await queryRunner.query(`ALTER TABLE \`libro_reclamaciones\` DROP COLUMN \`domicilio\``);
        await queryRunner.query(`ALTER TABLE \`libro_reclamaciones\` ADD \`domicilio\` varchar(255) COLLATE "utf8mb4_0900_ai_ci" NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`libro_reclamaciones\` CHANGE \`deleted_at\` \`deleted_at\` timestamp(6) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`perfiles\` CHANGE \`deleted_at\` \`deleted_at\` timestamp(6) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`abogados\` CHANGE \`objetivo\` \`objetivo\` varchar(255) COLLATE "utf8mb4_0900_ai_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`abogados\` CHANGE \`colegio\` \`colegio\` varchar(255) COLLATE "utf8mb4_0900_ai_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`abogados\` CHANGE \`ruc\` \`ruc\` varchar(255) COLLATE "utf8mb4_0900_ai_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`abogados\` CHANGE \`cip\` \`cip\` varchar(255) COLLATE "utf8mb4_0900_ai_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`abogados\` CHANGE \`deleted_at\` \`deleted_at\` timestamp(6) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`educaciones\` CHANGE \`abogado_id\` \`abogado_id\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`educaciones\` CHANGE \`descripcion\` \`descripcion\` varchar(255) COLLATE "utf8mb4_0900_ai_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`educaciones\` DROP COLUMN \`fecha_inicio\``);
        await queryRunner.query(`ALTER TABLE \`educaciones\` ADD \`fecha_inicio\` varchar(255) COLLATE "utf8mb4_0900_ai_ci" NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`educaciones\` DROP COLUMN \`fecha_fin\``);
        await queryRunner.query(`ALTER TABLE \`educaciones\` ADD \`fecha_fin\` varchar(255) COLLATE "utf8mb4_0900_ai_ci" NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`educaciones\` CHANGE \`deleted_at\` \`deleted_at\` timestamp(6) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`experiencias\` CHANGE \`abogado_id\` \`abogado_id\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`experiencias\` DROP COLUMN \`fecha_inicio\``);
        await queryRunner.query(`ALTER TABLE \`experiencias\` ADD \`fecha_inicio\` varchar(255) COLLATE "utf8mb4_0900_ai_ci" NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`experiencias\` DROP COLUMN \`fecha_fin\``);
        await queryRunner.query(`ALTER TABLE \`experiencias\` ADD \`fecha_fin\` varchar(255) COLLATE "utf8mb4_0900_ai_ci" NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`experiencias\` CHANGE \`deleted_at\` \`deleted_at\` timestamp(6) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`habilidades_duras\` CHANGE \`abogado_id\` \`abogado_id\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`habilidades_duras\` CHANGE \`deleted_at\` \`deleted_at\` timestamp(6) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`habilidades_blandas\` CHANGE \`abogado_id\` \`abogado_id\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`habilidades_blandas\` CHANGE \`deleted_at\` \`deleted_at\` timestamp(6) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`usuarios\` CHANGE \`cliente_id\` \`cliente_id\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`usuarios\` CHANGE \`abogado_id\` \`abogado_id\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`usuarios\` CHANGE \`activation_code_expires\` \`activation_code_expires\` timestamp NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`usuarios\` CHANGE \`activation_code\` \`activation_code\` varchar(255) COLLATE "utf8mb4_0900_ai_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`usuarios\` CHANGE \`direccion\` \`direccion\` varchar(255) COLLATE "utf8mb4_0900_ai_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`usuarios\` CHANGE \`deleted_at\` \`deleted_at\` timestamp(6) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`clientes\` CHANGE \`razon_social\` \`razon_social\` varchar(255) COLLATE "utf8mb4_0900_ai_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`clientes\` CHANGE \`deleted_at\` \`deleted_at\` timestamp(6) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`ofertas\` CHANGE \`cliente_id\` \`cliente_id\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`ofertas\` CHANGE \`fecha_expiracion\` \`fecha_expiracion\` varchar(255) COLLATE "utf8mb4_0900_ai_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`ofertas\` CHANGE \`estado\` \`estado\` varchar(255) COLLATE "utf8mb4_0900_ai_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`ofertas\` CHANGE \`salario_maximo\` \`salario_maximo\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`ofertas\` CHANGE \`salario_minimo\` \`salario_minimo\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`ofertas\` CHANGE \`experiencia_abogado\` \`experiencia_abogado\` varchar(255) COLLATE "utf8mb4_0900_ai_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`ofertas\` CHANGE \`duracion\` \`duracion\` varchar(255) COLLATE "utf8mb4_0900_ai_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`ofertas\` CHANGE \`documento_url\` \`documento_url\` varchar(255) COLLATE "utf8mb4_0900_ai_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`ofertas\` CHANGE \`titulo\` \`titulo\` varchar(255) COLLATE "utf8mb4_0900_ai_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`ofertas\` CHANGE \`uso\` \`uso\` varchar(255) COLLATE "utf8mb4_0900_ai_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`ofertas\` CHANGE \`deleted_at\` \`deleted_at\` timestamp(6) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`invitaciones\` CHANGE \`abogado_id\` \`abogado_id\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`invitaciones\` CHANGE \`oferta_id\` \`oferta_id\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`invitaciones\` DROP COLUMN \`fecha_respuesta\``);
        await queryRunner.query(`ALTER TABLE \`invitaciones\` ADD \`fecha_respuesta\` varchar(255) COLLATE "utf8mb4_0900_ai_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`invitaciones\` DROP COLUMN \`fecha_invitacion\``);
        await queryRunner.query(`ALTER TABLE \`invitaciones\` ADD \`fecha_invitacion\` varchar(255) COLLATE "utf8mb4_0900_ai_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`invitaciones\` CHANGE \`estado\` \`estado\` varchar(255) COLLATE "utf8mb4_0900_ai_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`invitaciones\` CHANGE \`mensaje\` \`mensaje\` text COLLATE "utf8mb4_0900_ai_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`invitaciones\` CHANGE \`deleted_at\` \`deleted_at\` timestamp(6) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`especialidades_oferta\` CHANGE \`especialidad_id\` \`especialidad_id\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`especialidades_oferta\` CHANGE \`oferta_id\` \`oferta_id\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`especialidades\` CHANGE \`deleted_at\` \`deleted_at\` timestamp(6) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`especialidades_abogado\` CHANGE \`especialidad_id\` \`especialidad_id\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`especialidades_abogado\` CHANGE \`abogado_id\` \`abogado_id\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`industrias_oferta\` CHANGE \`industria_id\` \`industria_id\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`industrias_oferta\` CHANGE \`oferta_id\` \`oferta_id\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`industrias\` CHANGE \`deleted_at\` \`deleted_at\` timestamp(6) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`industrias_abogado\` CHANGE \`industria_id\` \`industria_id\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`industrias_abogado\` CHANGE \`abogado_id\` \`abogado_id\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`servicios_oferta\` CHANGE \`servicio_id\` \`servicio_id\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`servicios_oferta\` CHANGE \`oferta_id\` \`oferta_id\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`servicios\` CHANGE \`deleted_at\` \`deleted_at\` timestamp(6) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`servicios_abogado\` CHANGE \`servicio_id\` \`servicio_id\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`servicios_abogado\` CHANGE \`abogado_id\` \`abogado_id\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`aplicaciones\` CHANGE \`abogado_id\` \`abogado_id\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`aplicaciones\` CHANGE \`oferta_id\` \`oferta_id\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`aplicaciones\` CHANGE \`salario_real\` \`salario_real\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`aplicaciones\` CHANGE \`impuesto\` \`impuesto\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`aplicaciones\` CHANGE \`comision\` \`comision\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`aplicaciones\` CHANGE \`salario_esperado\` \`salario_esperado\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`aplicaciones\` CHANGE \`estado\` \`estado\` varchar(255) COLLATE "utf8mb4_0900_ai_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`aplicaciones\` CHANGE \`selected_banco\` \`selected_banco\` varchar(255) COLLATE "utf8mb4_0900_ai_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`aplicaciones\` CHANGE \`numero_cuenta_cci\` \`numero_cuenta_cci\` varchar(255) COLLATE "utf8mb4_0900_ai_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`aplicaciones\` CHANGE \`numero_cuenta\` \`numero_cuenta\` varchar(255) COLLATE "utf8mb4_0900_ai_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`aplicaciones\` DROP COLUMN \`fecha_aplicacion\``);
        await queryRunner.query(`ALTER TABLE \`aplicaciones\` ADD \`fecha_aplicacion\` varchar(255) COLLATE "utf8mb4_0900_ai_ci" NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`aplicaciones\` CHANGE \`deleted_at\` \`deleted_at\` timestamp(6) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`respuestas_oferta\` CHANGE \`aplicacion_id\` \`aplicacion_id\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`respuestas_oferta\` CHANGE \`pregunta_id\` \`pregunta_id\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`respuestas_oferta\` CHANGE \`respuesta\` \`respuesta\` varchar(255) COLLATE "utf8mb4_0900_ai_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`respuestas_oferta\` CHANGE \`deleted_at\` \`deleted_at\` timestamp(6) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`preguntas_oferta\` CHANGE \`oferta_id\` \`oferta_id\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`preguntas_oferta\` CHANGE \`respuesta\` \`respuesta\` varchar(255) COLLATE "utf8mb4_0900_ai_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`preguntas_oferta\` CHANGE \`deleted_at\` \`deleted_at\` timestamp(6) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`trabajos\` CHANGE \`aplicacion_id\` \`aplicacion_id\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`trabajos\` CHANGE \`abogado_id\` \`abogado_id\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`trabajos\` CHANGE \`cliente_id\` \`cliente_id\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`trabajos\` CHANGE \`progreso\` \`progreso\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`trabajos\` CHANGE \`fecha_fin\` \`fecha_fin\` varchar(255) COLLATE "utf8mb4_0900_ai_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`trabajos\` CHANGE \`estado\` \`estado\` varchar(255) COLLATE "utf8mb4_0900_ai_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`trabajos\` CHANGE \`deleted_at\` \`deleted_at\` timestamp(6) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`pagos_abogado\` CHANGE \`abogado_id\` \`abogado_id\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`pagos_abogado\` CHANGE \`trabajo_id\` \`trabajo_id\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`pagos_abogado\` CHANGE \`tipo_pago\` \`tipo_pago\` varchar(255) COLLATE "utf8mb4_0900_ai_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`pagos_abogado\` CHANGE \`deleted_at\` \`deleted_at\` timestamp(6) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`progresos_trabajo\` CHANGE \`trabajo_id\` \`trabajo_id\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`progresos_trabajo\` CHANGE \`estado\` \`estado\` varchar(255) COLLATE "utf8mb4_0900_ai_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`progresos_trabajo\` CHANGE \`documento\` \`documento\` varchar(255) COLLATE "utf8mb4_0900_ai_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`progresos_trabajo\` CHANGE \`progreso\` \`progreso\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`progresos_trabajo\` CHANGE \`descripcion\` \`descripcion\` varchar(255) COLLATE "utf8mb4_0900_ai_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`progresos_trabajo\` CHANGE \`deleted_at\` \`deleted_at\` timestamp(6) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`pagos\` CHANGE \`abogado_id\` \`abogado_id\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`pagos\` CHANGE \`cliente_id\` \`cliente_id\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`pagos\` CHANGE \`trabajo_id\` \`trabajo_id\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`pagos\` CHANGE \`ruc\` \`ruc\` varchar(255) COLLATE "utf8mb4_0900_ai_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`pagos\` CHANGE \`nombre_factura\` \`nombre_factura\` varchar(255) COLLATE "utf8mb4_0900_ai_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`pagos\` CHANGE \`direccion_factura\` \`direccion_factura\` varchar(255) COLLATE "utf8mb4_0900_ai_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`pagos\` CHANGE \`monto_abogado\` \`monto_abogado\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`pagos\` CHANGE \`deleted_at\` \`deleted_at\` timestamp(6) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`files\` CHANGE \`trabajo_id\` \`trabajo_id\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`files\` CHANGE \`aplicacion_id\` \`aplicacion_id\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`files\` CHANGE \`oferta_id\` \`oferta_id\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`files\` CHANGE \`abogado_id\` \`abogado_id\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`files\` CHANGE \`id_front\` \`id_front\` varchar(255) COLLATE "utf8mb4_0900_ai_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`files\` CHANGE \`correo\` \`correo\` varchar(255) COLLATE "utf8mb4_0900_ai_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`files\` CHANGE \`dni\` \`dni\` varchar(255) COLLATE "utf8mb4_0900_ai_ci" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`files\` CHANGE \`deleted_at\` \`deleted_at\` timestamp(6) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`libro_reclamaciones\` CHANGE \`domicilio\` \`doomicilio\` varchar(255) COLLATE "utf8mb4_0900_ai_ci" NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`educaciones\` ADD CONSTRAINT \`FK_aa99d5b415317d1ae3fb4d844f5\` FOREIGN KEY (\`abogado_id\`) REFERENCES \`abogados\`(\`id\`) ON DELETE CASCADE ON UPDATE RESTRICT`);
        await queryRunner.query(`ALTER TABLE \`experiencias\` ADD CONSTRAINT \`FK_36c4a935245dc22dceb21568586\` FOREIGN KEY (\`abogado_id\`) REFERENCES \`abogados\`(\`id\`) ON DELETE CASCADE ON UPDATE RESTRICT`);
        await queryRunner.query(`ALTER TABLE \`habilidades_duras\` ADD CONSTRAINT \`FK_fd2feb177ffd5609bf1030cc457\` FOREIGN KEY (\`abogado_id\`) REFERENCES \`abogados\`(\`id\`) ON DELETE CASCADE ON UPDATE RESTRICT`);
        await queryRunner.query(`ALTER TABLE \`habilidades_blandas\` ADD CONSTRAINT \`FK_f6847ca550afe2c575adf0cc813\` FOREIGN KEY (\`abogado_id\`) REFERENCES \`abogados\`(\`id\`) ON DELETE CASCADE ON UPDATE RESTRICT`);
        await queryRunner.query(`ALTER TABLE \`usuarios\` ADD CONSTRAINT \`FK_5f4dc9b4cf1f7993658c5c22927\` FOREIGN KEY (\`cliente_id\`) REFERENCES \`clientes\`(\`id\`) ON DELETE RESTRICT ON UPDATE RESTRICT`);
        await queryRunner.query(`ALTER TABLE \`usuarios\` ADD CONSTRAINT \`FK_3d24dbe988e1186ec0bc6f4d165\` FOREIGN KEY (\`abogado_id\`) REFERENCES \`abogados\`(\`id\`) ON DELETE RESTRICT ON UPDATE RESTRICT`);
        await queryRunner.query(`ALTER TABLE \`ofertas\` ADD CONSTRAINT \`FK_bd29657fa3c0e45193334e16989\` FOREIGN KEY (\`cliente_id\`) REFERENCES \`clientes\`(\`id\`) ON DELETE CASCADE ON UPDATE RESTRICT`);
        await queryRunner.query(`ALTER TABLE \`invitaciones\` ADD CONSTRAINT \`FK_7a06641e7ce67e750ac3634a321\` FOREIGN KEY (\`oferta_id\`) REFERENCES \`ofertas\`(\`id\`) ON DELETE RESTRICT ON UPDATE RESTRICT`);
        await queryRunner.query(`ALTER TABLE \`invitaciones\` ADD CONSTRAINT \`FK_6a3e65a910f213c66b40e66b413\` FOREIGN KEY (\`abogado_id\`) REFERENCES \`abogados\`(\`id\`) ON DELETE CASCADE ON UPDATE RESTRICT`);
        await queryRunner.query(`ALTER TABLE \`especialidades_oferta\` ADD CONSTRAINT \`FK_5415a3af5f5df95ea327ce10636\` FOREIGN KEY (\`oferta_id\`) REFERENCES \`ofertas\`(\`id\`) ON DELETE CASCADE ON UPDATE RESTRICT`);
        await queryRunner.query(`ALTER TABLE \`especialidades_oferta\` ADD CONSTRAINT \`FK_13defeddcd8b6e6c6c32be6e68a\` FOREIGN KEY (\`especialidad_id\`) REFERENCES \`especialidades\`(\`id\`) ON DELETE RESTRICT ON UPDATE RESTRICT`);
        await queryRunner.query(`ALTER TABLE \`especialidades_abogado\` ADD CONSTRAINT \`FK_a17f29b9fcd3a66691c973b1d65\` FOREIGN KEY (\`abogado_id\`) REFERENCES \`abogados\`(\`id\`) ON DELETE CASCADE ON UPDATE RESTRICT`);
        await queryRunner.query(`ALTER TABLE \`especialidades_abogado\` ADD CONSTRAINT \`FK_9f3e8c9ae442054de33f1dfe915\` FOREIGN KEY (\`especialidad_id\`) REFERENCES \`especialidades\`(\`id\`) ON DELETE RESTRICT ON UPDATE RESTRICT`);
        await queryRunner.query(`ALTER TABLE \`industrias_oferta\` ADD CONSTRAINT \`FK_92a2e52e5974eb44e81d95c7873\` FOREIGN KEY (\`industria_id\`) REFERENCES \`industrias\`(\`id\`) ON DELETE RESTRICT ON UPDATE RESTRICT`);
        await queryRunner.query(`ALTER TABLE \`industrias_oferta\` ADD CONSTRAINT \`FK_37d0b01ae96c4012c22ec03478d\` FOREIGN KEY (\`oferta_id\`) REFERENCES \`ofertas\`(\`id\`) ON DELETE CASCADE ON UPDATE RESTRICT`);
        await queryRunner.query(`ALTER TABLE \`industrias_abogado\` ADD CONSTRAINT \`FK_ca773a8572eca954c744df62065\` FOREIGN KEY (\`industria_id\`) REFERENCES \`industrias\`(\`id\`) ON DELETE RESTRICT ON UPDATE RESTRICT`);
        await queryRunner.query(`ALTER TABLE \`industrias_abogado\` ADD CONSTRAINT \`FK_879d25a9cd6e5585fe4b586b684\` FOREIGN KEY (\`abogado_id\`) REFERENCES \`abogados\`(\`id\`) ON DELETE CASCADE ON UPDATE RESTRICT`);
        await queryRunner.query(`ALTER TABLE \`servicios_oferta\` ADD CONSTRAINT \`FK_73a4ab4c25d2f51c834b2ec6b5f\` FOREIGN KEY (\`servicio_id\`) REFERENCES \`servicios\`(\`id\`) ON DELETE RESTRICT ON UPDATE RESTRICT`);
        await queryRunner.query(`ALTER TABLE \`servicios_oferta\` ADD CONSTRAINT \`FK_5d4bebcd4ecc658ee52ef175b4d\` FOREIGN KEY (\`oferta_id\`) REFERENCES \`ofertas\`(\`id\`) ON DELETE CASCADE ON UPDATE RESTRICT`);
        await queryRunner.query(`ALTER TABLE \`servicios_abogado\` ADD CONSTRAINT \`FK_e874304bdce46393e0a14bd7b52\` FOREIGN KEY (\`abogado_id\`) REFERENCES \`abogados\`(\`id\`) ON DELETE CASCADE ON UPDATE RESTRICT`);
        await queryRunner.query(`ALTER TABLE \`servicios_abogado\` ADD CONSTRAINT \`FK_130434f31f7fd13567b51b51c7e\` FOREIGN KEY (\`servicio_id\`) REFERENCES \`servicios\`(\`id\`) ON DELETE RESTRICT ON UPDATE RESTRICT`);
        await queryRunner.query(`ALTER TABLE \`aplicaciones\` ADD CONSTRAINT \`FK_dc60683a7b4e357d4d5bffa1698\` FOREIGN KEY (\`abogado_id\`) REFERENCES \`abogados\`(\`id\`) ON DELETE CASCADE ON UPDATE RESTRICT`);
        await queryRunner.query(`ALTER TABLE \`aplicaciones\` ADD CONSTRAINT \`FK_c10d043d672443bb0f4a5106b25\` FOREIGN KEY (\`oferta_id\`) REFERENCES \`ofertas\`(\`id\`) ON DELETE CASCADE ON UPDATE RESTRICT`);
        await queryRunner.query(`ALTER TABLE \`respuestas_oferta\` ADD CONSTRAINT \`FK_f3e8713cb58b6c866b56ce9d3b8\` FOREIGN KEY (\`aplicacion_id\`) REFERENCES \`aplicaciones\`(\`id\`) ON DELETE CASCADE ON UPDATE RESTRICT`);
        await queryRunner.query(`ALTER TABLE \`respuestas_oferta\` ADD CONSTRAINT \`FK_ba7f1f593bbea35a0cb857a4f14\` FOREIGN KEY (\`pregunta_id\`) REFERENCES \`preguntas_oferta\`(\`id\`) ON DELETE CASCADE ON UPDATE RESTRICT`);
        await queryRunner.query(`ALTER TABLE \`preguntas_oferta\` ADD CONSTRAINT \`FK_d514c3c7a019638115c025fb5db\` FOREIGN KEY (\`oferta_id\`) REFERENCES \`ofertas\`(\`id\`) ON DELETE CASCADE ON UPDATE RESTRICT`);
        await queryRunner.query(`ALTER TABLE \`trabajos\` ADD CONSTRAINT \`FK_8099fd79318587093f6bf4b83bf\` FOREIGN KEY (\`abogado_id\`) REFERENCES \`abogados\`(\`id\`) ON DELETE CASCADE ON UPDATE RESTRICT`);
        await queryRunner.query(`ALTER TABLE \`trabajos\` ADD CONSTRAINT \`FK_31161729ac9b11c19eb0117f81a\` FOREIGN KEY (\`aplicacion_id\`) REFERENCES \`aplicaciones\`(\`id\`) ON DELETE RESTRICT ON UPDATE RESTRICT`);
        await queryRunner.query(`ALTER TABLE \`trabajos\` ADD CONSTRAINT \`FK_14b883832a7729bda1586e6af23\` FOREIGN KEY (\`cliente_id\`) REFERENCES \`clientes\`(\`id\`) ON DELETE CASCADE ON UPDATE RESTRICT`);
        await queryRunner.query(`ALTER TABLE \`pagos_abogado\` ADD CONSTRAINT \`FK_2779f73fd4282ba52c7b58958ab\` FOREIGN KEY (\`trabajo_id\`) REFERENCES \`trabajos\`(\`id\`) ON DELETE CASCADE ON UPDATE RESTRICT`);
        await queryRunner.query(`ALTER TABLE \`pagos_abogado\` ADD CONSTRAINT \`FK_100ca65fd5f8c99c052aa746156\` FOREIGN KEY (\`abogado_id\`) REFERENCES \`abogados\`(\`id\`) ON DELETE RESTRICT ON UPDATE RESTRICT`);
        await queryRunner.query(`ALTER TABLE \`progresos_trabajo\` ADD CONSTRAINT \`FK_577742b42abc00bcdb8f9b039b8\` FOREIGN KEY (\`trabajo_id\`) REFERENCES \`trabajos\`(\`id\`) ON DELETE CASCADE ON UPDATE RESTRICT`);
        await queryRunner.query(`ALTER TABLE \`pagos\` ADD CONSTRAINT \`FK_ef854a8e14a8828e5586afbe215\` FOREIGN KEY (\`abogado_id\`) REFERENCES \`abogados\`(\`id\`) ON DELETE CASCADE ON UPDATE RESTRICT`);
        await queryRunner.query(`ALTER TABLE \`pagos\` ADD CONSTRAINT \`FK_ed9e32bfd96f130ffa862adbcc9\` FOREIGN KEY (\`trabajo_id\`) REFERENCES \`trabajos\`(\`id\`) ON DELETE CASCADE ON UPDATE RESTRICT`);
        await queryRunner.query(`ALTER TABLE \`pagos\` ADD CONSTRAINT \`FK_3fa5cbaf018b1004741ff1afca5\` FOREIGN KEY (\`cliente_id\`) REFERENCES \`clientes\`(\`id\`) ON DELETE CASCADE ON UPDATE RESTRICT`);
        await queryRunner.query(`ALTER TABLE \`files\` ADD CONSTRAINT \`FK_889080ced09b49ebb4c8fb005db\` FOREIGN KEY (\`abogado_id\`) REFERENCES \`abogados\`(\`id\`) ON DELETE CASCADE ON UPDATE RESTRICT`);
        await queryRunner.query(`ALTER TABLE \`files\` ADD CONSTRAINT \`FK_6ea47570ecb59c0fd0ce6b784be\` FOREIGN KEY (\`aplicacion_id\`) REFERENCES \`aplicaciones\`(\`id\`) ON DELETE CASCADE ON UPDATE RESTRICT`);
        await queryRunner.query(`ALTER TABLE \`files\` ADD CONSTRAINT \`FK_45969913e1276f23c44c04ab30b\` FOREIGN KEY (\`trabajo_id\`) REFERENCES \`trabajos\`(\`id\`) ON DELETE CASCADE ON UPDATE RESTRICT`);
        await queryRunner.query(`ALTER TABLE \`files\` ADD CONSTRAINT \`FK_3847bce5b766d69c2d0e320b1ef\` FOREIGN KEY (\`oferta_id\`) REFERENCES \`ofertas\`(\`id\`) ON DELETE CASCADE ON UPDATE RESTRICT`);
    }

}
